### ISSUE TITLE
RSS feed?

### ISSUE THREAD

**Issue by kivikakk** [gabizon103/gabizon103.github.io#1]
I'd love to follow your blog, but it's not possible without an RSS feed! Would you be open to adding one?

It looks like you're using Zola? The docs [seem to suggest](https://www.getzola.org/documentation/templates/feeds/) it's enough to add this to `config.toml`:

```toml
generate_feeds = true
```

**Comment by gabizon103** [comment]
thanks for the suggestion, should be added now. happy reading!

**Comment by kivikakk** [comment]
Thanks so much! :white_heart:
